default_platform(:ios)
platform :ios do
  desc "Preflight Check"
  before_all do
    ENV["FASTLANE_EXPLICIT_OPEN_SIMULATOR"] == "2"
    setup_circle_ci
  end

  desc "lint"
  lane :lint do
    swiftlint(
      mode: :lint,
      output_file: "swiftlint.xml",
      config_file: ".swiftlint.yml",
      ignore_exit_status: false,
      raise_if_swiftlint_error: true,
      reporter: "junit"
    )
  end

  desc "test framework"
  lane :test do
    scan(
      project: "MaterialUI.xcodeproj",
      devices: ["iPhone XS Max"],
      scheme: "MaterialUITests",
      clean: true,
      code_coverage: true
    )

    codecov_reporter
  end
end
